# Generated by Django 5.0.7 on 2025-01-28 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venta',
            old_name='servicio',
            new_name='servicios',
        ),
    ]
